-- ============================================================
-- RetailOS POS — Supabase Schema
-- Run this entire file in your Supabase SQL Editor
-- ============================================================

-- PRODUCTS
create table if not exists products (
  id        bigint generated by default as identity primary key,
  name      text           not null,
  sku       text           not null unique,
  category  text           not null,
  price     numeric(10,2)  not null,
  cost      numeric(10,2)  not null,
  stock     integer        not null default 0,
  low_stock integer        not null default 10,
  icon      text           not null default '🛒',
  created_at timestamptz   default now()
);

-- EXPENSES
create table if not exists expenses (
  id          bigint generated by default as identity primary key,
  description text           not null,
  category    text           not null,
  amount      numeric(10,2)  not null,
  date        date           not null,
  ref         text           default '',
  notes       text           default '',
  created_at  timestamptz    default now()
);

-- TRANSACTIONS
create table if not exists transactions (
  id         text           primary key,   -- e.g. TXN-0001
  time       text           not null,
  payment    text           not null,      -- cash, card, gcash, maya, credit
  subtotal   numeric(10,2)  not null,
  tax        numeric(10,2)  not null,
  total      numeric(10,2)  not null,
  cogs       numeric(10,2)  not null default 0,
  date       text           not null,
  paid       boolean        default true,  -- false for credit sales until paid
  due_date   text           default null,  -- e.g. '2026-06-11' for credit sales
  created_at timestamptz    default now()
);

-- TRANSACTION ITEMS
create table if not exists transaction_items (
  id             bigint generated by default as identity primary key,
  transaction_id text           references transactions(id) on delete cascade,
  product_id     bigint         not null,
  name           text           not null,
  price          numeric(10,2)  not null,
  qty            integer        not null,
  icon           text           not null default '🛒'
);

-- ============================================================
-- ROW LEVEL SECURITY
-- Enable these if you add Supabase Auth later.
-- For now the anon key has full access (internal POS tool).
-- ============================================================
-- alter table products          enable row level security;
-- alter table expenses          enable row level security;
-- alter table transactions      enable row level security;
-- alter table transaction_items enable row level security;
-- create policy "allow_all" on products          for all using (true) with check (true);
-- create policy "allow_all" on expenses          for all using (true) with check (true);
-- create policy "allow_all" on transactions      for all using (true) with check (true);
-- create policy "allow_all" on transaction_items for all using (true) with check (true);

-- ============================================================
-- SEED DATA  (run once to pre-populate products + expenses)
-- ============================================================
insert into products (name, sku, category, price, cost, stock, low_stock, icon) values
  ('Coca-Cola 1.5L',        'BEV-001', 'Beverages',      75,  55,  48,  10, '🥤'),
  ('Lucky Me Pancit',       'SNK-001', 'Snacks',          15,   9, 120,  20, '🍜'),
  ('Safeguard Soap',        'PC-001',  'Personal Care',   52,  38,  30,  10, '🧼'),
  ('Tide Powder 1kg',       'HH-001',  'Household',      125,  90,  25,   8, '🧺'),
  ('Sky Flakes',            'SNK-002', 'Snacks',          28,  18,  80,  15, '🍘'),
  ('Nestlé Fresh Milk',     'DRY-001', 'Dairy',           89,  68,  12,  10, '🥛'),
  ('Del Monte Tomato Sauce','CAN-001', 'Canned Goods',    45,  30,  60,  12, '🥫'),
  ('Gardenia Loaf',         'BRD-001', 'Bread & Bakery',  65,  48,   8,   5, '🍞'),
  ('Sprite 1.5L',           'BEV-002', 'Beverages',       72,  52,  36,  10, '🍋'),
  ('Boy Bawang',            'SNK-003', 'Snacks',          18,  11,   6,  10, '🧄'),
  ('Knorr Chicken Cubes',   'CAN-002', 'Canned Goods',    35,  22,  90,  15, '🫙'),
  ('Selecta Ice Cream',     'FRZ-001', 'Frozen',         185, 140,  14,   5, '🍨')
on conflict (sku) do nothing;

insert into expenses (description, category, amount, date, ref, notes) values
  ('Monthly Rent',        'Rent',      8000, '2026-05-01', '',         'May rent'),
  ('Meralco Electric Bill','Utilities', 2400, '2026-05-05', 'MEL-8823', ''),
  ('Staff Salary - Ana',  'Salaries',  5000, '2026-05-05', '',         'Semi-monthly')
on conflict do nothing;
